# Generated by Django 3.1.7 on 2021-04-21 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carthasinventorybook',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carthasinventorybook',
            name='cart_cart',
            field=models.ForeignKey(db_column='Cart_cart_id', on_delete=django.db.models.deletion.DO_NOTHING, to='store.cart'),
        ),
    ]
