# Generated by Django 3.1.7 on 2021-04-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='getsPromos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_number',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
