# Generated by Django 3.1.7 on 2021-03-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
