# Generated by Django 3.1.7 on 2021-04-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='usercol',
        ),
        migrations.AddField(
            model_name='user1',
            name='user_active',
            field=models.BooleanField(db_column='user_active', default=False),
        ),
    ]
