# Generated by Django 3.1.7 on 2021-04-12 00:29

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='card_number',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=16)),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='cvv',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True)),
        ),
    ]
