# Generated by Django 3.1.7 on 2021-03-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210330_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentcard_card_number',
            new_name='paymentCard_card_number',
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
