# Generated by Django 3.1.7 on 2021-04-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210410_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='getsPromos',
            field=models.BooleanField(default=False),
        ),
    ]
