# Generated by Django 3.1.7 on 2021-04-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210421_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='carthasinventorybook',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
