# Generated by Django 3.1.7 on 2021-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210422_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='user_active',
            field=models.CharField(db_column='user_active', default='active', max_length=45),
        ),
    ]
