# Generated by Django 3.1.7 on 2021-04-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210410_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='getsPromos',
            new_name='receive_promotions',
        ),
    ]
