# Generated by Django 3.1.7 on 2021-04-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210412_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='online_bookstore/store/static/store/images/'),
        ),
    ]
