# Generated by Django 3.1.7 on 2021-04-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210410_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='startdate',
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, db_column='end_date', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(blank=True, db_column='start_date', null=True),
        ),
    ]
