# Generated by Django 3.1.7 on 2021-04-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210410_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='usertype',
            field=models.BooleanField(db_column='userType', default=True),
        ),
    ]
