# Generated by Django 3.1.7 on 2021-04-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210423_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='user_code',
            field=models.CharField(default='123', max_length=45),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user1_user_id',
            field=models.OneToOneField(db_column='User1_user_id', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='store.user1'),
        ),
        migrations.AlterField(
            model_name='user1',
            name='user_active',
            field=models.BooleanField(db_column='user_active', default=False),
        ),
    ]
