# Generated by Django 3.1.7 on 2021-04-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210410_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='usertype',
        ),
        migrations.AddField(
            model_name='user1',
            name='user_suspend',
            field=models.BooleanField(db_column='user_suspend', default=False),
        ),
    ]
