# Generated by Django 3.1.7 on 2021-04-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='user1_user_id',
            field=models.ForeignKey(blank=True, db_column='User1_user_id', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.user1'),
        ),
    ]
