# Generated by Django 3.1.7 on 2021-04-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210425_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='user1_user_id',
            field=models.ForeignKey(db_column='User1_user_id', default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.user1'),
        ),
    ]
