# Generated by Django 3.1.7 on 2021-04-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210425_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentCard_card_id',
            field=models.ForeignKey(db_column='PaymentCard_card_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.paymentcard'),
        ),
    ]
