# Generated by Django 3.1.7 on 2021-04-26 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210425_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedbook',
            name='order_id',
            field=models.ForeignKey(db_column='Order.order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
    ]
