# Generated by Django 3.1.7 on 2021-04-26 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210425_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carthasinventorybook',
            name='book_bookid',
            field=models.ForeignKey(db_column='Book_bookID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.book'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='book_bookid',
            field=models.ForeignKey(db_column='Book_bookID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.book'),
        ),
    ]
