# Generated by Django 3.1.7 on 2021-04-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210429_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='user1_user_id',
            field=models.OneToOneField(db_column='User1_user_id', default='', on_delete=django.db.models.deletion.CASCADE, to='store.user1'),
        ),
    ]
