# Generated by Django 3.1.7 on 2021-04-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210429_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carthasinventorybook',
            name='cart_cart',
            field=models.ForeignKey(db_column='Cart_cart_id', on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_order',
            field=models.ForeignKey(db_column='Order_order_id', default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
    ]
